project_id = "eypfkyqshggbjoadaefc"

[functions.generate-invitation]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.melhor-envio-webhook]
verify_jwt = false

[functions.get-tenant-public]
verify_jwt = false

[functions.get-invitation]
verify_jwt = false

[functions.get-contract]
verify_jwt = false

[functions.sign-contract]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-product-checkout]
verify_jwt = false